### ISSUE TITLE
Failed to load extenstion 

### ISSUE THREAD

**Issue by frickypickle** [Lumm1t/epodreczniki-advisor#2]
File
~\Desktop\epodreczniki-advisor-master
Error
Could not load css 'epodrecznikiadvisor.min.css' for content script.
Could not load manifest.
Any fix for this
Da sie to naprawic?

**Comment by alexszolowicz-blockether** [comment]
Download it from releases page.
https://github.com/Lumm1t/epodreczniki-advisor/releases/tag/v1.1 - first file.

**Comment by frickypickle** [comment]
Thank you! It worked!

**Comment by rox24p** [comment]
I am doing something wrong or it just doesn't work. On e-podreczniki it doesn't show answers, just this.
![Screenshot_1](https://user-images.githubusercontent.com/74143811/98467784-72a47d80-21d7-11eb-8fa3-81c3dff448db.png)
